### ISSUE TITLE
XML layout of Admin Dashboard

### ISSUE THREAD

**Issue by aarav0012** [bsoc-bitbyte/DigiGate24#10]
Create an XML layout of Admin Dashboard and a card which will be used in Recycler View  based on the design given in [Figma](https://www.figma.com/design/kKT5N7cP7FYCwyMUMGOoaa/DigiGate?node-id=0-1&t=pzQtJ65GNlIh5yhQ-0)

Your layout must follow these guidelines :

1. Use Constraint Layout to ensure the layout is responsive to all screen sizes.
2. Adhere to the given Figma design
3. Follow the specified naming convention for each view group ID to maintain consistency and clarity.
4. Create a separate xml layout file for card.
5. Only add a empty container for Recycler View in Admin Dashboard.

**Comment by ayushsaksena30** [comment]
@aarav0012 I would Iike to work on this issue. My approach will be to use two custom Buttons to switch between separate Fragments for Entry and Exit. I'll also use TextView element to show the date. I'll display the texts, margins and UI styles from the Figma file provided and follow the naming conventions. I'll also wrap everything in constraint layout to make the screen more responsive.
For the card, I'll use cardView to display rounded corners and use nested Linear Layout to display the texts properly.
Thank You

**Comment by AyushNarsian** [comment]
Good afternoon maintainer @aarav0012 I would like to work on the issue. I would use edit textbox with the date type input. I would make 2 custom button with gradient background and rounded corners. To make the containers I will use recycler view. I'll use constraint layout to make the app responsive to different screen sizes. I'll bind the elements in the constraint layout to each other to make it more responsive.
Thank You!

**Comment by aniket0742** [comment]
@aarav0012 I would like to work on this issue. I would use the mentioned Constraint layout to bind the content and ensure it adapts well to different screen sizes. I'll use EditText for date input with correct input type setting. I'll initialize the Recycler View in the activity and set it up with an empty adapter. I'll match the Figma design exactly and ensure using consistent IDs and names and follow the suggested guidelines. 
Thank You.

**Comment by aarav0012** [comment]
@aniket0742 go ahead
