### ISSUE TITLE
XML layout of Admin Scanner

### ISSUE THREAD

**Issue by aarav0012** [bsoc-bitbyte/DigiGate24#7]
create an XML layout of Admin Scanner based on the design given in [Figma](https://www.figma.com/design/kKT5N7cP7FYCwyMUMGOoaa/DigiGate?node-id=0-1&t=pzQtJ65GNlIh5yhQ-0)

Your layout must follow these guidelines :

1. Use Constraint Layout to ensure the layout is responsive to all screen sizes.
2. Adhere to the given Figma design
3. Follow the specified naming convention for each view group ID to maintain consistency and clarity.

**Comment by AyushNarsian** [comment]
@aarav0012 Sir I would like to work on this issue. I would use Constraint Layout and in it i will use Text view image view and buttons with measurements according to the figma provided. I will use the defined colors from colors xml file to provide colors to buttons.

**Comment by zephyr004** [comment]
Maintainer @aarav0012,
I would like to work on the issue regarding the XML layout of Admin Scanner. Following the Figma design , I will use the ConstraintLayout as mentioned. I will use TextView for displaying the title and other text, ImageView to display the scanner, and the two buttons as required.
I will follow the specified guidelines and also ensure proper alignment, styling, and spacing of the views.
Thankyou.

**Comment by ayushsaksena30** [comment]
@aarav0012 I would like to work on this issue. My approach will be to use TextView to display all texts and View to display the line with width for length and height for thickness. I will also use ImageView to display the scanner image and wrap all the content in constraint layout to increase screen responsiveness. I'll use button to create profile and display text.

I will use two buttons and import the custom background and implement the appropriate UI styles according to the Figma provided.

Thank You

**Comment by aarav0012** [comment]
@zephyr004 go ahead
